version: "3.7"
services:
  node:
    build: .
    volumes:
      - .:/app
    ports:
      - "${PORT}:8080"
  db:
    image: "mysql/mysql-server:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ROOT_HOST: 'root'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - 8081:80
volumes:
  data: